[2025-04-24T19:20:04.452+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-24T19:20:04.475+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-24T19:10:00+00:00 [queued]>
[2025-04-24T19:20:04.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-24T19:10:00+00:00 [queued]>
[2025-04-24T19:20:04.482+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-24T19:20:04.493+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Kafka_Producer> on 2025-04-24 19:10:00+00:00
[2025-04-24T19:20:04.499+0000] {standard_task_runner.py:63} INFO - Started process 1674 to run task
[2025-04-24T19:20:04.502+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'Kafka_Producer', 'scheduled__2025-04-24T19:10:00+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpah6a08y1']
[2025-04-24T19:20:04.504+0000] {standard_task_runner.py:91} INFO - Job 303: Subtask Kafka_Producer
[2025-04-24T19:20:04.539+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-24T19:10:00+00:00 [running]> on host 6555ac884751
[2025-04-24T19:20:04.608+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='Kafka_Producer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T19:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-24T19:10:00+00:00'
[2025-04-24T19:20:04.609+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-24T19:20:04.622+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T19:20:04.623+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/Scripts/alpha_vantage_producer.py']
[2025-04-24T19:20:04.638+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T19:20:05.456+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.21.0.6', 9092)]>: connecting to kafka:9092 [('172.21.0.6', 9092) IPv4]
[2025-04-24T19:20:05.458+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.21.0.6', 9092)]>: Broker version identified as 2.6
[2025-04-24T19:20:05.458+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.21.0.6', 9092)]>: Connection complete.
[2025-04-24T19:20:05.458+0000] {subprocess.py:93} INFO - INFO:kafka_producer:Alpha Vantage producer started for symbols: ['IBM', 'AAPL', 'MSFT', 'TSLA']
[2025-04-24T19:20:11.874+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.21.0.6', 9092)]>: connecting to kafka:9092 [('172.21.0.6', 9092) IPv4]
[2025-04-24T19:20:11.874+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.21.0.6', 9092)]>: Connection complete.
[2025-04-24T19:20:11.874+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.21.0.6', 9092)]>: Closing connection.
[2025-04-24T19:20:11.879+0000] {subprocess.py:93} INFO - INFO:kafka_producer:Published data for IBM to topic 'stock-prices'
[2025-04-24T19:20:49.888+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-24T19:20:49.888+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-24T19:20:49.890+0000] {process_utils.py:132} INFO - Sending 15 to group 1674. PIDs of all processes in the group: [1675, 1674]
[2025-04-24T19:20:49.890+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1674
[2025-04-24T19:20:49.891+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-24T19:20:49.891+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-24T19:20:49.892+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-24T19:20:49.917+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1675, status='terminated', started='19:20:04') (1675) terminated with exit code None
[2025-04-24T19:20:49.918+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1674, status='terminated', exitcode=0, started='19:20:03') (1674) terminated with exit code 0
